name: gen_simpy
channels:
  - conda-forge
dependencies:
  - ipytest=0.14.2
  - joblib=1.2.0
  - jupyter-book=1.0.2
  - jupyterlab=4.2.3
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.8.1
  - numpy=1.26.0
  - pandas=2.1.3
  - pip=23.3.1
  - pytest=8.2.1
  - python=3.10.13
  - simpy=4.1.1
  - sim-tools=0.5.0
  - scipy=1.11.3
  - streamlit=1.34.0
  - pip:
    - pygount==1.8.0

