name: gen_simpy_apps
channels:
  - conda-forge
dependencies:
  - matplotlib=3.8.1
  - numpy=1.26.0
  - pandas=2.1.3
  - pip=23.3.1
  - python=3.10.13
  - simpy=4.1.1
  - sim-tools=0.5.0
  - streamlit=1.34.0

